---
name: Scaffold Terraform Module
run-name: Scaffold Terraform Module (${{inputs.module_path}})
on:
  workflow_dispatch:
    inputs:
      module_path:
        description: "module path"
        required: true
      template_dir:
        type: choice
        default: templates/module-hello
        options:
          - templates/module-hello
jobs:
  scaffold:
    runs-on: ubuntu-latest
    env:
      TFACTION_MODULE_PATH: ${{inputs.module_path}}
      TFACTION_MODULE_TEMPLATE_DIR: ${{inputs.template_dir}}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: aquaproj/aqua-installer@928a2ee4243a9ee8312d80dc8cbaca88fb602a91 # v2.2.0
        with:
          aqua_version: v2.24.0
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          # pull_requests:write - Create pull requests
          # contents:write - Push commits
          permissions: >-
            {
              "pull_requests": "write",
              "contents": "write"
            }
          repositories: >-
            ["${{github.event.repository.name}}"]

      - uses: suzuki-shunsuke/tfaction/scaffold-module@72536e0b22961437dbca58cb4f3ea20a6b50b58f # v1.2.1-1
        with:
          github_token: ${{steps.generate_token.outputs.token}}

      - uses: suzuki-shunsuke/tfaction/create-scaffold-module-pr@72536e0b22961437dbca58cb4f3ea20a6b50b58f # v1.2.1-1
        with:
          github_token: ${{steps.generate_token.outputs.token}}
