name: Self-Approve Action

on:
  pull_request:

jobs:
  self-approve-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Self-Approve Action
        uses: nicklegan/github-repo-self-approve-action@86495ef73587b7ebbda94ec221f814ddde1677ba # v1.0.0
        if: github.actor == 'matchan26'
        with:
          appid: ${{ secrets.APP_ID }}
          privatekey: ${{ secrets.PRIVATE_KEY }}
          installationid: ${{ secrets.APP_INSTALLATION_ID }}
