---
name: plan
on:
  workflow_call:
    inputs:
      targets:
        required: true
        type: string
      ref:
        required: true
        type: string
    secrets:
      gh_app_id:
        required: true
      gh_app_private_key:
        required: true


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.targets }}
